[package]
name = "day-night"
version = "0.1.0"
authors = ["Max Verevkin <me@maxverevkin.tk>"]
edition = "2018"
description = "A simple program that executes shell commands based on the time of day"

[dependencies]
sunrise = "1.0"
chrono = "0.4"
clap = "2.33"
